
###
GET http://localhost:5555/emplist


###
POST http://localhost:5555/emplist
Content-Type: application/json

{
	"empname" : "Mahesh",
	"dept" : "HR",
	"city" : "Pune",
	"salary": "10000"
}


###
DELETE http://localhost:5555/emplist/6556ede4570668c17bf21385



###
PATCH http://localhost:5555/emplist
Content-Type: application/json

{
	"empname" : "Ganesh",
	"dept" : "HR",
	"city" : "Darjeeling",
	"salary": "99000",
	"id" : "6555bbbefbdb11d7587c251a"
}


###
POST  http://localhost:5555/productlist
Content-Type: application/json

{
	"pname" : "Mango Green",
	"price" : "200",
	"qty" : "30",
	"photo": "2.jpg"
}


###
GET http://localhost:5555/productlist


###
DELETE http://localhost:5555/productlist/65570ecb10b6b0d466927b8d


###
GET http://localhost:5555/productlist/Banana


###
PUT http://localhost:5555/productlist/65572fc185160e81dd058455