
###
GET http://localhost:5555/emplist


###
POST http://localhost:5555/emplist
Content-Type: application/json

{
	"empname" : "Mahesh",
	"dept" : "HR",
	"city" : "Pune",
	"salary": "10000"
}


###
DELETE http://localhost:5555/emplist/6556ede4570668c17bf21385



###
PATCH http://localhost:5555/emplist
Content-Type: application/json

{
	"empname" : "Ganesh",
	"dept" : "HR",
	"city" : "Darjeeling",
	"salary": "99000",
	"id" : "6555bbbefbdb11d7587c251a"
}


###
POST  http://localhost:5555/productlist
Content-Type: application/json

{
	"pname" : "Mango Green",
	"price" : "200",
	"qty" : "30",
	"photo": "2.jpg"
}


###
GET http://localhost:5555/productlist


###
DELETE http://localhost:5555/productlist/65570ecb10b6b0d466927b8d


###
GET http://localhost:5555/productlist/Banana


###
PUT http://localhost:5555/productlist/65572fc185160e81dd058455


###
GET http://localhost:5555/cart


###
POST http://localhost:5555/cart
Content-Type: application/json

{
  "pname": "pname",
  "qty": "re",
  "price":" ce",
  "photo": "oto",
  "userid": "rrid"
}


###
DELETE http://localhost:5555/cart/6558b0c28eee671ac97e2bde


###
PUT http://localhost:5555/cart
Content-Type: application/json

{
  "qty": "4",
 	"id": "6558bb9a7b92fc3ba7eb2b58"
}


###
POST http://localhost:5555/order
Content-Type: application/json

{
	"name":"Ganesh",
  "city": "Kailash",
  "mobile": "989879879",
  "email": "ganesh@shiv.com",
  "address": "Himalaya Mountain, India",
  "itemlist": {"test": "Hari Bol"},
  "userid": "1234567"
}

